travis:
  secure:
    BINSTAR_TOKEN: QA8OwzWJhwIZAwN4XHU55jvynhMaYoxQTmwcPtsYegkeHAm2R6Mi1Ml73twUhHik+C4i1TtRSUCgpYFiEjgDRWbZTeOPuOsAJDp51ndEnE6ihk1wQkgiwbqPMGFCy2pG/ICjIbPBKguZT7BhXF3hGD7Iz+61PVmpb73zsLOMkr/BMZGkIkn46WrWyMH38t7a9U2IqLX23DShUpoDGghC29g4fZl2/DdH9zu+u34lNKSS/nevXGvx8jGIev+Jq0Th7XRT0EPNeyd2H1gNNBqtDabTJM1PSCG7OU8YboxuyUx9TVF2oTPyiaULtxNgFQh4wLKLviStGtMKgMdz566yYhR/kJPh2NnTZeDf6qD9vgKGiVjQQXZjWalgwXmPyf09GihmBPk/DdAg1wZKhC5vRXk9i3ROp+RUlEacjk65LYacVPAOME5WhqnikBoTv+U6Okk1IVog67mrWf8BAePzkbmBZeFv0j8J5Qt4siJ3twPMc++g0h0xBwGc42iyi3wLFYFmLWmNJTf5Mnli8pcgNiAUNvgQJgPpWNctxY1d+ywNr/wnHEvcbxVsg3g3RIkbHyjWdL+2dYHfEaPVbIFP4Ue9M5nO2QJITYTlIKjMWS+B9VQpfVTvfjkdaSw2uo4dM6zuH1c/XfgJ/oyQ7+bYKS1WDbt6BL+YrT7NAFX9efc=
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
